[package]
name = "CC2018-Project1"
version = "0.1.0"
edition = "2024"

[dependencies]
raylib = "5.5.1"
rodio = "0.17"
minifb = "0.28" 
nalgebra = "0.34.1"
tobj = "4.0.2"
image = "0.25"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
